version: '3.8'
services:
  db:
    image: mysql
    restart: always
    container_name: mysqlconnection
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: serverless_api
    ports:
      - "3306:3306"
    volumes:
      - /home/sinoed/data/db:/data/db

  serverless:
    image: murilloalcantara/serverless
    container_name: serverless
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8080:8080"